const gender = [
  {title: 'Random', icon: 'auto-fix', value: 'random'},
  {title: 'Male', icon: 'gender-male', value: 'male'},
  {title: 'Female', icon: 'gender-female', value: 'female'},
];

const countries = [
  {
    value: 'de',
    icon: 'de',
    flag: require('../assets/flags/de.webp'),
    title: 'German',
  },
  {
    value: 'fr',
    icon: 'fr',
    flag: require('../assets/flags/fr.webp'),
    title: 'French',
  },
  {
    value: 'ja',
    icon: 'jp',
    flag: require('../assets/flags/jp.webp'),
    title: 'Japanese',
  },
  {
    value: 'en_IN',
    icon: 'in',
    flag: require('../assets/flags/in.webp'),
    title: 'English (India)',
  },
  {
    value: 'zh_CN',
    icon: 'cn',
    flag: require('../assets/flags/cn.webp'),
    title: 'Chinese (China)',
  },
  {
    value: 'en_CA',
    icon: 'ca',
    flag: require('../assets/flags/ca.webp'),
    title: 'English (Canada)',
  },
  {
    value: 'en_AU',
    icon: 'au',
    flag: require('../assets/flags/au.webp'),
    title: 'English (Australia)',
  },
  {
    value: 'en_US',
    icon: 'us',
    flag: require('../assets/flags/us.webp'),
    title: 'English (United States)',
  },
  {
    value: 'en_GB',
    icon: 'gb',
    flag: require('../assets/flags/gb.webp'),
    title: 'English (Great Britain)',
  },
  {
    value: 'af_ZA',
    icon: 'za',
    flag: require('../assets/flags/za.webp'),
    title: 'Afrikaans (South Africa)',
  },
  {
    value: 'ar',
    icon: 'sa',
    flag: require('../assets/flags/sa.webp'),
    title: 'Arabic',
  },
  {
    value: 'az',
    icon: 'az',
    flag: require('../assets/flags/az.webp'),
    title: 'Azerbaijani',
  },
  {
    value: 'cs_CZ',
    icon: 'cz',
    flag: require('../assets/flags/cz.webp'),
    title: 'Czech (Czechia)',
  },
  {
    value: 'da',
    icon: 'dk',
    flag: require('../assets/flags/dk.webp'),
    title: 'Danish',
  },
  {
    value: 'de_AT',
    icon: 'at',
    flag: require('../assets/flags/at.webp'),
    title: 'German (Austria)',
  },
  {
    value: 'de_CH',
    icon: 'ch',
    flag: require('../assets/flags/ch.webp'),
    title: 'German (Switzerland)',
  },
  {
    value: 'dv',
    icon: 'mv',
    flag: require('../assets/flags/mv.webp'),
    title: 'Maldivian',
  },
  {
    value: 'el',
    icon: 'gr',
    flag: require('../assets/flags/gr.webp'),
    title: 'Greek',
  },
  {
    value: 'en',
    icon: 'us',
    flag: require('../assets/flags/us.webp'),
    title: 'English',
  },
  {
    value: 'en_AU_ocker',
    icon: 'au',
    flag: require('../assets/flags/au.webp'),
    title: 'English (Australia Ocker)',
  },
  {
    value: 'en_BORK',
    icon: 'us',
    flag: require('../assets/flags/us.webp'),
    title: 'English (Bork)',
  },
  {
    value: 'en_GH',
    icon: 'gh',
    flag: require('../assets/flags/gh.webp'),
    title: 'English (Ghana)',
  },
  {
    value: 'en_HK',
    icon: 'hk',
    flag: require('../assets/flags/hk.webp'),
    title: 'English (Hong Kong)',
  },
  {
    value: 'en_IE',
    icon: 'ie',
    flag: require('../assets/flags/ie.webp'),
    title: 'English (Ireland)',
  },
  {
    value: 'en_NG',
    icon: 'ng',
    flag: require('../assets/flags/ng.webp'),
    title: 'English (Nigeria)',
  },
  {
    value: 'en_ZA',
    icon: 'za',
    flag: require('../assets/flags/za.webp'),
    title: 'English (South Africa)',
  },
  {
    value: 'eo',
    icon: 'de',
    flag: require('../assets/flags/de.webp'),
    title: 'Esperanto',
  },
  {
    value: 'es',
    icon: 'es',
    flag: require('../assets/flags/es.webp'),
    title: 'Spanish',
  },
  {
    value: 'es_MX',
    icon: 'mx',
    flag: require('../assets/flags/mx.webp'),
    title: 'Spanish (Mexico)',
  },
  {
    value: 'fa',
    icon: 'ir',
    flag: require('../assets/flags/ir.webp'),
    title: 'Farsi/Persian',
  },
  {
    value: 'fi',
    icon: 'fi',
    flag: require('../assets/flags/fi.webp'),
    title: 'Finnish',
  },
  {
    value: 'fr_BE',
    icon: 'be',
    flag: require('../assets/flags/be.webp'),
    title: 'French (Belgium)',
  },
  {
    value: 'fr_CA',
    icon: 'ca',
    flag: require('../assets/flags/ca.webp'),
    title: 'French (Canada)',
  },
  {
    value: 'fr_CH',
    icon: 'ch',
    flag: require('../assets/flags/ch.webp'),
    title: 'French (Switzerland)',
  },
  {
    value: 'fr_LU',
    icon: 'lu',
    flag: require('../assets/flags/lu.webp'),
    title: 'French (Luxembourg)',
  },
  {
    value: 'fr_SN',
    icon: 'sn',
    flag: require('../assets/flags/sn.webp'),
    title: 'French (Senegal)',
  },
  {
    value: 'he',
    icon: 'il',
    flag: require('../assets/flags/il.webp'),
    title: 'Hebrew',
  },
  {
    value: 'hr',
    icon: 'hr',
    flag: require('../assets/flags/hr.webp'),
    title: 'Croatian',
  },
  {
    value: 'hu',
    icon: 'hu',
    flag: require('../assets/flags/hu.webp'),
    title: 'Hungarian',
  },
  {
    value: 'hy',
    icon: 'am',
    flag: require('../assets/flags/am.webp'),
    title: 'Armenian',
  },
  {
    value: 'id_ID',
    icon: 'id',
    flag: require('../assets/flags/id.webp'),
    title: 'Indonesian (Indonesia)',
  },
  {
    value: 'it',
    icon: 'it',
    flag: require('../assets/flags/it.webp'),
    title: 'Italian',
  },
  {
    value: 'ka_GE',
    icon: 'ge',
    flag: require('../assets/flags/ge.webp'),
    title: 'Georgian (Georgia)',
  },
  {
    value: 'ko',
    icon: 'kr',
    flag: require('../assets/flags/kr.webp'),
    title: 'Korean',
  },
  {
    value: 'lv',
    icon: 'lv',
    flag: require('../assets/flags/lv.webp'),
    title: 'Latvian',
  },
  {
    value: 'mk',
    icon: 'mk',
    flag: require('../assets/flags/mk.webp'),
    title: 'Macedonian',
  },
  {
    value: 'nb_NO',
    icon: 'no',
    flag: require('../assets/flags/no.webp'),
    title: 'Norwegian (Norway)',
  },
  {
    value: 'ne',
    icon: 'np',
    flag: require('../assets/flags/np.webp'),
    title: 'Nepali',
  },
  {
    value: 'nl',
    icon: 'nl',
    flag: require('../assets/flags/nl.webp'),
    title: 'Dutch',
  },
  {
    value: 'nl_BE',
    icon: 'be',
    flag: require('../assets/flags/be.webp'),
    title: 'Dutch (Belgium)',
  },
  {
    value: 'pl',
    icon: 'pl',
    flag: require('../assets/flags/pl.webp'),
    title: 'Polish',
  },
  {
    value: 'pt_BR',
    icon: 'br',
    flag: require('../assets/flags/br.webp'),
    title: 'Portuguese (Brazil)',
  },
  {
    value: 'pt_PT',
    icon: 'pt',
    flag: require('../assets/flags/pt.webp'),
    title: 'Portuguese (Portugal)',
  },
  {
    value: 'ro',
    icon: 'ro',
    flag: require('../assets/flags/ro.webp'),
    title: 'Romanian',
  },
  {
    value: 'ro_MD',
    icon: 'md',
    flag: require('../assets/flags/md.webp'),
    title: 'Romanian (Moldova)',
  },
  {
    value: 'ru',
    icon: 'ru',
    flag: require('../assets/flags/ru.webp'),
    title: 'Russian',
  },
  {
    value: 'sk',
    icon: 'sk',
    flag: require('../assets/flags/sk.webp'),
    title: 'Slovak',
  },
  {
    value: 'sr_RS_latin',
    icon: 'rs',
    flag: require('../assets/flags/rs.webp'),
    title: 'Serbian (Serbia, Latin)',
  },
  {
    value: 'sv',
    icon: 'se',
    flag: require('../assets/flags/se.webp'),
    title: 'Swedish',
  },
  {
    value: 'th',
    icon: 'th',
    flag: require('../assets/flags/th.webp'),
    title: 'Thai',
  },
  {
    value: 'tr',
    icon: 'tr',
    flag: require('../assets/flags/tr.webp'),
    title: 'Turkish',
  },
  {
    value: 'uk',
    icon: 'ua',
    flag: require('../assets/flags/ua.webp'),
    title: 'Ukrainian',
  },
  {
    value: 'ur',
    icon: 'pk',
    flag: require('../assets/flags/pk.webp'),
    title: 'Urdu',
  },
  {
    value: 'uz_UZ_latin',
    icon: 'uz',
    flag: require('../assets/flags/uz.webp'),
    title: 'Uzbek (Uzbekistan, Latin)',
  },
  {
    value: 'vi',
    icon: 'vn',
    flag: require('../assets/flags/vn.webp'),
    title: 'Vietnamese',
  },
  {
    value: 'yo_NG',
    icon: 'ng',
    flag: require('../assets/flags/ng.webp'),
    title: 'Yoruba (Nigeria)',
  },
  {
    value: 'zh_TW',
    icon: 'tw',
    flag: require('../assets/flags/tw.webp'),
    title: 'Chinese (Taiwan)',
  },
  {
    value: 'zu_ZA',
    icon: 'za',
    flag: require('../assets/flags/za.webp'),
    title: 'Zulu (South Africa)',
  },
];

const ages = [
  {title: 'Random', icon: 'auto-fix', value: {minAge: 18, maxAge: 65}},
  {
    title: '18 to 24',
    icon: 'clock-time-eight-outline',
    value: {minAge: 18, maxAge: 24},
  },
  {
    title: '25 to 34',
    icon: 'clock-time-eight-outline',
    value: {minAge: 25, maxAge: 34},
  },
  {
    title: '35 to 44',
    icon: 'clock-time-eight-outline',
    value: {minAge: 35, maxAge: 44},
  },
  {
    title: '45 to 54',
    icon: 'clock-time-eight-outline',
    value: {minAge: 45, maxAge: 54},
  },
  {
    title: '55 to 64',
    icon: 'clock-time-eight-outline',
    value: {minAge: 55, maxAge: 64},
  },
  {
    title: '65 to 74',
    icon: 'clock-time-eight-outline',
    value: {minAge: 65, maxAge: 74},
  },
  {
    title: '75+',
    icon: 'clock-time-eight-outline',
    value: {minAge: 75, maxAge: 104},
  },
];

const support_iban = [
  'AL',
  'AD',
  'AT',
  'AZ',
  'BH',
  'BE',
  'BA',
  'BR',
  'BG',
  'CR',
  'HR',
  'CY',
  'CZ',
  'DK',
  'DO',
  'TL',
  'EE',
  'FO',
  'FI',
  'FR',
  'GE',
  'DE',
  'GI',
  'GR',
  'GL',
  'GT',
  'HU',
  'IS',
  'IE',
  'IL',
  'IT',
  'JO',
  'KZ',
  'XK',
  'KW',
  'LV',
  'LB',
  'LI',
  'LT',
  'LU',
  'MK',
  'MT',
  'MR',
  'MU',
  'MC',
  'MD',
  'ME',
  'NL',
  'NO',
  'PK',
  'PS',
  'PL',
  'PT',
  'QA',
  'RO',
  'SM',
  'SA',
  'RS',
  'SK',
  'SI',
  'ES',
  'SE',
  'CH',
  'TN',
  'TR',
  'AE',
  'GB',
  'VG',
];

export {gender, countries, ages, support_iban};
