const gender = [
  {title: 'Random', icon: 'auto-fix', value: 'random'},
  {title: 'Male', icon: 'gender-male', value: 'male'},
  {title: 'Female', icon: 'gender-female', value: 'female'},
];

const countries = [
  {value: 'de', icon: 'de', title: 'German'},
  {value: 'fr', icon: 'fr', title: 'French'},
  {value: 'ja', icon: 'jp', title: 'Japanese'},
  {value: 'en_IN', icon: 'in', title: 'English (India)'},
  {value: 'zh_CN', icon: 'cn', title: 'Chinese (China)'},
  {value: 'en_CA', icon: 'ca', title: 'English (Canada)'},
  {value: 'en_AU', icon: 'au', title: 'English (Australia)'},
  {value: 'en_US', icon: 'us', title: 'English (United States)'},
  {value: 'en_GB', icon: 'gb', title: 'English (Great Britain)'},
  {value: 'af_ZA', icon: 'za', title: 'Afrikaans (South Africa)'},
  {value: 'ar', icon: 'sa', title: 'Arabic'},
  {value: 'az', icon: 'az', title: 'Azerbaijani'},
  {value: 'cs_CZ', icon: 'cz', title: 'Czech (Czechia)'},
  {value: 'da', icon: 'dk', title: 'Danish'},
  {value: 'de_AT', icon: 'at', title: 'German (Austria)'},
  {value: 'de_CH', icon: 'ch', title: 'German (Switzerland)'},
  {value: 'dv', icon: 'mv', title: 'Maldivian'},
  {value: 'el', icon: 'gr', title: 'Greek'},
  {value: 'en', icon: 'us', title: 'English'},
  {value: 'en_AU_ocker', icon: 'au', title: 'English (Australia Ocker)'},
  {value: 'en_BORK', icon: 'us', title: 'English (Bork)'},
  {value: 'en_GH', icon: 'gh', title: 'English (Ghana)'},
  {value: 'en_HK', icon: 'hk', title: 'English (Hong Kong)'},
  {value: 'en_IE', icon: 'ie', title: 'English (Ireland)'},
  {value: 'en_NG', icon: 'ng', title: 'English (Nigeria)'},
  {value: 'en_ZA', icon: 'za', title: 'English (South Africa)'},
  {value: 'eo', icon: 'de', title: 'Esperanto'},
  {value: 'es', icon: 'es', title: 'Spanish'},
  {value: 'es_MX', icon: 'mx', title: 'Spanish (Mexico)'},
  {value: 'fa', icon: 'ir', title: 'Farsi/Persian'},
  {value: 'fi', icon: 'fi', title: 'Finnish'},
  {value: 'fr_BE', icon: 'be', title: 'French (Belgium)'},
  {value: 'fr_CA', icon: 'ca', title: 'French (Canada)'},
  {value: 'fr_CH', icon: 'ch', title: 'French (Switzerland)'},
  {value: 'fr_LU', icon: 'lu', title: 'French (Luxembourg)'},
  {value: 'fr_SN', icon: 'sn', title: 'French (Senegal)'},
  {value: 'he', icon: 'il', title: 'Hebrew'},
  {value: 'hr', icon: 'hr', title: 'Croatian'},
  {value: 'hu', icon: 'hu', title: 'Hungarian'},
  {value: 'hy', icon: 'am', title: 'Armenian'},
  {value: 'id_ID', icon: 'id', title: 'Indonesian (Indonesia)'},
  {value: 'it', icon: 'it', title: 'Italian'},
  {value: 'ka_GE', icon: 'ge', title: 'Georgian (Georgia)'},
  {value: 'ko', icon: 'kr', title: 'Korean'},
  {value: 'lv', icon: 'lv', title: 'Latvian'},
  {value: 'mk', icon: 'mk', title: 'Macedonian'},
  {value: 'nb_NO', icon: 'no', title: 'Norwegian (Norway)'},
  {value: 'ne', icon: 'np', title: 'Nepali'},
  {value: 'nl', icon: 'nl', title: 'Dutch'},
  {value: 'nl_BE', icon: 'be', title: 'Dutch (Belgium)'},
  {value: 'pl', icon: 'pl', title: 'Polish'},
  {value: 'pt_BR', icon: 'br', title: 'Portuguese (Brazil)'},
  {value: 'pt_PT', icon: 'pt', title: 'Portuguese (Portugal)'},
  {value: 'ro', icon: 'ro', title: 'Romanian'},
  {value: 'ro_MD', icon: 'md', title: 'Romanian (Moldova)'},
  {value: 'ru', icon: 'ru', title: 'Russian'},
  {value: 'sk', icon: 'sk', title: 'Slovak'},
  {value: 'sr_RS_latin', icon: 'rs', title: 'Serbian (Serbia, Latin)'},
  {value: 'sv', icon: 'se', title: 'Swedish'},
  {value: 'th', icon: 'th', title: 'Thai'},
  {value: 'tr', icon: 'tr', title: 'Turkish'},
  {value: 'uk', icon: 'ua', title: 'Ukrainian'},
  {value: 'ur', icon: 'pk', title: 'Urdu'},
  {value: 'uz_UZ_latin', icon: 'uz', title: 'Uzbek (Uzbekistan, Latin)'},
  {value: 'vi', icon: 'vn', title: 'Vietnamese'},
  {value: 'yo_NG', icon: 'ng', title: 'Yoruba (Nigeria)'},
  {value: 'zh_TW', icon: 'tw', title: 'Chinese (Taiwan)'},
  {value: 'zu_ZA', icon: 'za', title: 'Zulu (South Africa)'},
];

const ages = [
  {title: 'Random', icon: 'auto-fix', value: {minAge: 18, maxAge: 65}},
  {
    title: '18 to 24',
    icon: 'clock-time-eight-outline',
    value: {minAge: 18, maxAge: 24},
  },
  {
    title: '25 to 34',
    icon: 'clock-time-eight-outline',
    value: {minAge: 25, maxAge: 34},
  },
  {
    title: '35 to 44',
    icon: 'clock-time-eight-outline',
    value: {minAge: 35, maxAge: 44},
  },
  {
    title: '45 to 54',
    icon: 'clock-time-eight-outline',
    value: {minAge: 45, maxAge: 54},
  },
  {
    title: '55 to 64',
    icon: 'clock-time-eight-outline',
    value: {minAge: 55, maxAge: 64},
  },
  {
    title: '65 to 74',
    icon: 'clock-time-eight-outline',
    value: {minAge: 65, maxAge: 74},
  },
  {
    title: '75+',
    icon: 'clock-time-eight-outline',
    value: {minAge: 75, maxAge: 104},
  },
];

const support_iban = [
  'AL',
  'AD',
  'AT',
  'AZ',
  'BH',
  'BE',
  'BA',
  'BR',
  'BG',
  'CR',
  'HR',
  'CY',
  'CZ',
  'DK',
  'DO',
  'TL',
  'EE',
  'FO',
  'FI',
  'FR',
  'GE',
  'DE',
  'GI',
  'GR',
  'GL',
  'GT',
  'HU',
  'IS',
  'IE',
  'IL',
  'IT',
  'JO',
  'KZ',
  'XK',
  'KW',
  'LV',
  'LB',
  'LI',
  'LT',
  'LU',
  'MK',
  'MT',
  'MR',
  'MU',
  'MC',
  'MD',
  'ME',
  'NL',
  'NO',
  'PK',
  'PS',
  'PL',
  'PT',
  'QA',
  'RO',
  'SM',
  'SA',
  'RS',
  'SK',
  'SI',
  'ES',
  'SE',
  'CH',
  'TN',
  'TR',
  'AE',
  'GB',
  'VG',
];

export {gender, countries, ages, support_iban};
